pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }

    options {
        ansiColor('xterm')
    }

    stages {
        stage('Destroying the infrastructure') {
            steps {
                dir('../wearify-infra') {
                    sh 'terraform init'
                    sh 'terraform destroy --auto-approve'
                }
            }
        }
    }
}