pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }

    options {
        ansiColor('xterm')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Copy TF State') {
            steps {
                sh 'cp /var/jenkins_home/workspace/wearify-pipeline/wearify-infra/terraform.tfstate /var/jenkins_h
ome/workspace/wearify-demolish/wearify-infra/terraform.tfstate'
            }
        }
        stage('Destroying the infrastructure') {
            steps {
                dir('../wearify-infra') {
                    sh 'terraform init'
                    sh 'terraform destroy --auto-approve'
                }
            }
        }
    }
}