pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }

    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello Shubham"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'cd wearify-infra'
                sh 'terraform init'
                sh 'terraform apply --auto-approve'
            }
        }
    }
}