def repChanges = ''
def isFirstBuild = false

pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }

    options {
        ansiColor('xterm')
    }

    stages {
        stage('Scanning the changes'){
            steps{
                script {
                    isFirstBuild = currentBuild.previousBuild == null
                    repChanges = sh(
                        script: "git diff --name-only HEAD~1 HEAD",
                        returnStdout: true
                    ).trim()
                }
                echo "Updated files are ${repChanges}"
                dir('kubernetes/deployments') {
                    echo 'Scanned the changes from directory...'
                }
            }
        }
        stage('Replace terraform directory') {
            when {
                expression {
                    return isFirstBuild
                }
            }
            steps {
                dir('wearify-infra')
                {
                    script {
                        sh 'chmod -R 777 /var/lib/jenkins/workspace/wearify-pipeline/wearify-infra/wearify_keys/wearify_keypair.pem'
                        sh 'cp -R /var/lib/jenkins/workspace/wearify-pipeline/wearify-infra/* /var/lib/jenkins/workspace/wearify-monitoring/wearify-infra/'
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Setting up the monitoring') {
            when {
                expression {
                    isFirstBuild || repChanges.contains("kubernetes/monitoring")
                }
            }
            steps
            {
                dir("wearify-infra") {
                    script {
                        env.WEARIFY_MASTER_IP_ADDR = sh(script: "terraform output -raw wearify_master_node_ipv4_addr", returnStdout: true).trim()
                        env.WEARIFY_KEY_PATH = sh(script: "terraform output -raw wearify_key_location", returnStdout: true).trim()
                    
                        sh 'chmod 700 wearify_keys'
                        sh 'chmod 400 wearify_keys/wearify_keypair.pem'
                        sh '''ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i ${WEARIFY_KEY_PATH} ubuntu@${WEARIFY_MASTER_IP_ADDR} chmod +x ./monitoring/deployMonitoring.sh'''             
                        sh '''ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i ${WEARIFY_KEY_PATH} ubuntu@${WEARIFY_MASTER_IP_ADDR} ./monitoring/deployMonitoring.sh'''             
                    }
                }
            }
        }    
    }
}