apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-wearify-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/backend"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-wearify-pvc
  namespace: wearify
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: wearify
data:
  CLUSTER_API_ENDPOINT_ROUTE: /api
  CLUSTER_API_SERVER_PORT: "5000"
  CLUSTER_API_SERVER_HOST: "0.0.0.0"
  REMOTE_FRONTEND: "true"
  CLUSTER_MONGO_URL: wearify-mongodb
  CLUSTER_POSTGRES_HOST: wearify-postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-wearify-deployment
  namespace: wearify
  labels:
    app: backend-wearify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-wearify
  template:
    metadata:
      labels:
        app: backend-wearify
    spec:
      initContainers:
        - name: backend-data-copy
          image: shubh1917/wearify-backend
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /mnt/images /mnt/data;
              cp -r /home/wearify/app/images/* /mnt/images/ || true;
              cp -r /home/wearify/app/data/* /mnt/data/ || true;
          volumeMounts:
            - name: backend-storage
              mountPath: /mnt/images
              subPath: images
            - name: backend-storage
              mountPath: /mnt/data
              subPath: data
      containers:
        - name: backend-wearify
          image: shubh1917/wearify-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: backend-storage
              mountPath: /home/wearify/app/images
              subPath: images
            - name: backend-storage
              mountPath: /home/wearify/app/data
              subPath: data
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-wearify-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wearify-backend
  namespace: wearify
spec:
  selector:
    app: backend-wearify
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
