apiVersion: apps/v1
kind: Deployment
metadata:
  name: wearify-frontend
  namespace: wearify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wearify-frontend
  template:
    metadata:
      labels:
        app: wearify-frontend
    spec:
      containers:
        - name: react-nginx
          imagePullPolicy: Always
          image: shubh1917/wearify-frontend
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wearify-frontend
  namespace: wearify
spec:
  selector:
    app: wearify-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
