apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-wearify-pv
  labels:
    type: nosql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongodb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-wearify-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: nosql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-wearify-deployment
  labels:
    app: mongodb-wearify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-wearify
  template:
    metadata:
      labels:
        app: mongodb-wearify
    spec:
      containers:
        - name: mongo-wearify
          image: shubh1917/wearify-mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-wearify-pvc
