apiVersion: v1
kind: Service
metadata:
  name: wearify-backend
  namespace: wearify
spec:
  selector:
    app: backend-wearify
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
