apiVersion: v1
kind: Service
metadata:
  name: wearify-mongodb
  namespace: wearify
spec:
  selector:
    app: mongodb-wearify
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
